# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
author: cwisoftware
site_url: http://cwi.com.br/
email: contato@cwi.com.br
twitter: cwisoftware
github: cwisoftware

title: CWI Blog
description: >
  Blog colaborativo da CWI

baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://cwisoftware.github.io" # the base hostname & protocol for your site

permalink: /:categories/:title

# Build settings
markdown: kramdown

exclude:
  # folders
  - docs
  - vendor
  - scripts

  # files
  - Gemfile
  - Gemfile.lock
  - README.md
  - Vagrantfile
